Users/urls.py
from django.urls import path
from . import views
app_name = 'account'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contactUs, name='contactus'),
]

src/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path("back/account/", include("account.API.urls")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/include/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'homepage:home' %}">Home</a>
        <a class="nav-link" href="{% url 'homepage:aboutus' %}">About Us</a>
        <a class="nav-link" href="{% url 'contact:contactus' %}">Contact Us</a>
        <a class="nav-link " aria-disabled="true" href="/admin"> Admin</a>
          {% if request.user.is_authenticated %}
              <a class="nav-link " aria-disabled="true" > Hello {{user.username}}</a>
              <a class="btn btn-outline-danger " aria-disabled="true" href="{% url 'account:logout' %}" > Log Out</a>

          {% else %}
              <a class="btn btn-outline-success " aria-disabled="true" href="{% url 'account:login' %}"> Login</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>