src/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("post_detail/<int:post_id>/", views.post_detail, name="post-detail"),
    path("like_post/<int:post_id>/", views.like_post, name="like-post"),
    path("add_comment/<int:post_id>/", views.add_comment, name="add-comment"),
    path(
        "add_reply/<int:post_id>/<int:comment_id>/", views.add_reply, name="add-reply"
    ),
    path(
        "delete_comment/<int:comment_id>/", views.delete_comment, name="delete-comment"
    ),
]

src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

src/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path("back/account/", include("account.API.urls")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

src/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('aboutus', views.about, name='about'),
    path('list/', views.product_list, name='product_list'),
    path(
        'list/<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category',
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail',
    ),
    path('addorder/', views.add_order, name="add_order"),
    
]

src/shop/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import Account

# class crm(models):
#     phone = models.CharField(max_length=13)
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    image = models.ImageField(
        upload_to='Category/',
        blank=True
    )
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category', args=[self.slug]
        )


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    image2 = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    size = models.CharField(max_length=100, blank=True, null=True)
    weight = models.CharField(max_length=100, blank=True, null=True)
    deliveryTime= models.CharField(max_length=100, blank=True, null=True)
    description = RichTextUploadingField(blank=True)
    Specifications = RichTextUploadingField(blank=True)
    price = models.PositiveBigIntegerField(default=0)
    discount = models.PositiveBigIntegerField(default=0, max_length=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    def get_final_price(self):
        return abs(int((self.price * (self.discount - 100)) / 100))
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])




class SpecialOrder(models.Model):

    user = models.ForeignKey(Account,  related_name='special',null=True,  on_delete=models.SET_NULL)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to="SpecialOrder/", null=True, blank=True)

    class Meta:
        verbose_name = "سفارش"
        verbose_name_plural = "سفارش ها"

    def __str__(self):
        return self.name




class SpecialSale(models.Model):
    products = models.ManyToManyField(Product, related_name="special")

    

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label="تعداد"
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

src/shop/forms.py
from django import forms

from shop.models import SpecialOrder




class addOrderForm(forms.ModelForm):
    class Meta:
        model = SpecialOrder
        fields = (
            "name",
            "phone",
            "description",
            "image"
        )

    def save(self, commit=True, *args, **kwargs):
        order = super().save(commit=False)
        if commit:
            order.save()

        return order

src/shop/views.py
from django.shortcuts import get_object_or_404, redirect, render

from cart.forms import CartAddProductForm
from shop.forms import addOrderForm
from .models import Category, Product,SpecialSale
from django.views.generic import  ListView
from django.db.models import Q 
# from .recommender import Recommender
class SearchResultsView(ListView):
    model = Product
    template_name = 'shop/product/search_results.html'
    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
  
        return object_list
def add_order(request):

    if request.method == 'POST':
        form = addOrderForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
        return redirect("shop:home")
    return redirect("shop:home")


def home(request):
    All = Product.objects.all()
    length = len(All)
    products = All.filter(available=True)[:4]
    chipest = All.order_by("price")[:4]
    special =SpecialSale.objects.all()[:1]
    mid = All.order_by("price")[length/2-3:length/2+1]
    categories = Category.objects.all()
    expensive = All.order_by("-price")[:4]
    return render(
        request,
        'shop/product/home.html',
        {
            'products': products,
            'chipest': chipest,
            'categories': categories,
            'mid': mid,
            'special':special,
            'expensive': expensive,
        },)
def product_list(request, category_slug=None):

    category = None
    categories = Category.objects.all()

    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
           
        },
    )


def product_detail(request, id, slug):

 
    product = get_object_or_404(
        Product, id=id, slug=slug
    )
    cart_product_form = CartAddProductForm()
    # r = Recommender()
    # recommended_products = r.suggest_products_for([product], 4)
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form,
            
            # 'recommended_products': recommended_products,
        },
    )

def about(request):
    return render(request, "shop/aboutus.html")

src/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block custommeta %}
<meta name="product_id" content="{{product.id}}">
<meta name="product_name" content="{{product.name}}">
<meta property="og:image" content="{{ product.image.url }}">
<meta name="product_price" content="{{product.get_final_price }}">
<meta name="product_old_price" content="{{ product.price }}">

{% if product.available == True %} <meta name="availability" content="instock">{% else %} <meta name="availability" content="outofstock">{% endif %}
      
{% endblock custommeta %}
{% block content %}
  <div class="w-full mt-36   lg:px-10 lg:flex lg:justify-evenly lg:min-h-screen"> 
      <div class="w-11/12 mx-auto m-2 lg:w-2/5 lg:px-20 lg:size-[500px] overflow-visible">
        <div >
          <div class="overflow-visible">
            <img id="image1" class="w-full mx-auto lg:w-[500px] lg:hover:w-[600px]" src="{% if product.image %}{{ product.image.url }}{% else %}
            {%  static 'img/no_image.png' %}{% endif %}" aria-details="True">
      
            <img id="image2" class="hidden w-full mx-auto lg:w-[500px] lg:hover:w-[600px]" src="{% if product.image2 %}{{ product.image2.url }}{% else %}
            {%  static 'img/no_image.png' %}{% endif %}" aria-details="True">
          </div>
          <div class="w-full h-32 flex justify-center items-center" dir="ltr">
            <img id="thumbimage1" onclick="imageopener(1)" class="w-16 h-16 blur-[1px]" src="{% if product.image %}{{ product.image.url }}{% endif %}" aria-details="True">

            <img id="thumbimage2" onclick="imageopener(2)" class=" w-16 h-16 ml-10 blur-[1px]" src="{% if product.image2 %}{{ product.image2.url }}{% endif %}" aria-details="True">
          </div>
        </div>


      </div>
    <div class="w-full px-5 lg:p-0 lg:w-1/2">
      <div class="recommendations">
        <h2 class="flex items-center justify-start">
          <a class="button 
          text-blue-200 font-AnjomanMax_SemiBold w-40 my-2" href="{{ product.category.get_absolute_url }}">
            {{ product.category }}  <span class="text-gray-500">/</span>
          </a>
        </h2>
      </div>
      <h1 class="font-AnjomanMax_ExBold text-xl">{{ product.name }}</h1>
      <i class="fa-solid fa-star text-yellow-300"></i>
      <i class="fa-solid fa-star text-yellow-300"></i>
      <i class="fa-solid fa-star text-yellow-300"></i>
      <i class="fa-solid fa-star text-yellow-300"></i>
      <i class="fa-solid fa-star text-yellow-300"></i>
      <hr>

      <p class="font-AnjomanMax_ExBold text-green-600 my-2">{{ product.price | intcomma }} تومان</p>
      <div class="w-full flex justify-start">
        {% if product.available == True %}
        <div class="w-full">
        <form class="w-full lg:w-full flex justify-between items-center" action="{% url "cart:cart_add" product.id %}" method="post">
          <div class="flex">
            <label for="id_quantity">تعداد:</label>
        <select class="text-center  w-16 rounded-sm mx-2" name="quantity" id="id_quantity">
          <option value="1">1</option>
        
          <option value="2">2</option>
        
          <option value="3">3</option>
        
          <option value="4">4</option>
        
          <option value="5">5</option>
        
          <option value="6">6</option>
        
          <option value="7">7</option>
        
          <option value="8">8</option>
        
          <option value="9">9</option>
        
          <option value="10">10</option>
        
          <option value="11">11</option>
        
          <option value="12">12</option>
        
          <option value="13">13</option>
        
          <option value="14">14</option>
        
          <option value="15">15</option>
        
          <option value="16">16</option>
        
          <option value="17">17</option>
        
          <option value="18">18</option>
        
          <option value="19">19</option>
        
          <option value="20">20</option>
        
        </select>  
        <input type="hidden" name="override" value="False" id="id_override">
        </div>
          {% csrf_token %}
          <button class="button flex justify-center w-80 bg-green-200  shadow-inner shadow-green-400 m-2  text-black lg:my-4" type="submit" > افزودن به سبد <img class="size-6" src="{% static 'img/cart.png' %}" alt=""></button>
        </form>
        {% if product.deliveryTime %}
            <p class="text-purple-700"> {{product.deliveryTime}}</p>
        {% else %}
        <p class="text-purple-700"> آماده سازی و ارسال 6 روز کاری</p>
        {% endif %}
      </div>
        {% else %}
        <div>
          <button class="button w-60 bg-gray-200  shadow-inner shadow-gray-400 my-2  text-black lg:my-4" type="submit" > افزودن به سبد <img class="size-6" src="{% static 'img/cart.png' %}" alt=""></button>
        <div>
          <p class="text-red-500 text-sm"> موجود نیست </p>
          {% comment %} <!-- <form action="{% url 'shop:crm' %}">
          {% csrf_token %}
          <div class="flex  items-center space-x-2">
            <input class="text-center h-12 border rounded-md mx-2" name="phone" type="text" placeholder="شماره تلفن"> <button class="button w-32 bg-green-200  shadow-inner shadow-green-400 my-2  flex justify-center text-black lg:my-4" type="submit">ثبت</button>
          </div>
        </form> --> {% endcomment %}
        </div>
        </div>
        {% endif %}
      </div>
    <div class="mt-4">
      <button id="desbtn1" onclick="win('description')" class="w-32 border-0 bg-gray-100 text-gray-600 text-[14px]"> معرفی </button>
      <button id="desbtn2"  onclick="win('Specifications')" class="w-32 border-0 bg-gray-100 text-gray-600 text-[18px]"> مشخصات </button>
      <hr>
      <div id="description" class="text-justify w-full p-4 hidden">
        {{ product.description|safe }}
      </div>
      <div id="Specifications" class="text-justify w-full p-4 ">
        <ul>
          <li>جنس محصول:
            برنز</li>
            <li>ضمانت نامه کتبی اصالت محصول:
              دارد</li>
              {% if product.size %}
              <li>اندازه: {{product.size}}</li>
              {% endif %}
              {% if product.weight %}
              <li>وزن : {{product.weight}}
              </li>
              {% endif %}
              <li>ارسال رایگان در شهر همدان:
                دارد</li>
                <li>ارسال به سراسر کشور:
                  دارد</li>
        </ul>
        {{ product.Specifications|safe }}
      </div>
    </div>
    </div>
  </div>
{% endblock %}

{% block customJs %}
<script>
  function win(variable) {
    let description = document.getElementById('description');
    let Specifications = document.getElementById('Specifications');
    let desbtn1 = document.getElementById('desbtn1');
    let desbtn2 = document.getElementById('desbtn2');
    if (variable == "description") {

      desbtn1.style.fontSize = "18px";
      desbtn2.style.fontSize = "14px";
      description.style.display = "block";
      Specifications.style.display = "none";

    }else if("Specifications"){
      description.style.display = "none";
      Specifications.style.display = "block";
      desbtn1.style.fontSize = "14px";
      desbtn2.style.fontSize = "18px";
    }
  }
  let image1 = document.getElementById('image1');
  let image2 = document.getElementById('image2');

  function imageopener(param) {
    switch (param) {
      case 1:
        image1.style.display = 'block';
        image2.style.display = 'none';

        break;
      case 2:
        image1.style.display = 'none';
        image2.style.display = 'block';

        break;
    
      default:
        break;
    }
  }
</script>
{% endblock %}

src/templates/shop/product/home.html
{% extends "shop/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}محصولات{% endif %}
{% endblock %}

{% block custommeta %}
<meta name="title" content="ارسی یک بازار مطمئن و ارزان, برای محصولات برنزی است.">
<meta name="description"
      content="  ارسی بورس کلاهای برنزی با کیفیت و قیمت مناسب برای شما همین حالا خرید خودتون رو سفارش بدید. و منزل خودتون رو به شیکترین محصولات برنزی مجهز کنید  ">
<meta name="keywords" content="فروشگاه برنز, برنز, ارسی, برنز ارسی, برنز با کیفیت, دکوراسیون, برنز اصل, محصولات برنجی, برنجی ارسی, مجسمه برنزی, لوستر, لوستر برنزی">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
{% endblock custommeta %}
{% block content %}
{#  Hero  #}

<!-- Hero Section -->
{% include 'shop/components/Hero.html' %}
 <!-- End Hero Section  -->

  <div id="main" class="w-full md:w-[80%] h-auto   mb-10 md:mb-24 mx-auto">

    <div class="flex gap-4 text-gray-500 h-16 items-center">
      <a href="#newest">جدیدترین</a>
      <a href="#chipest">ارزانترین</a>
      <a href="#popular">محبوبترین</a>
      <a href="#expensive">گرانترین</a>
    </div>
    <div>
      <div class="bg-red-800 text-white lg:rounded-xl p-2" style="background-image: url({% static 'img/bg.jpg' %});">
      <div class="w-full flex justify-between lg:px-10 font-AnjomanMax_Bold ">
        <h2>فروش ویژه</h2>
      </div>
      <div class="  overflow-scroll ">
        <div class="inline-flex gap-4 w-auto lg:py-6">
        {% for item in special %}
          {% for product in item.products.all %}
          <a href="{{ product.get_absolute_url }}">
            <div class=" w-40 lg:w-52  bg-white text-black rounded-xl text-sm  mx-auto lg:mx-2  ">
                
                  <img class="w-auto rounded-xl" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
         
                <div class="productDetail">
                  <p class="font-AnjomanMax_Thin text-sm flex flex-wrap  lg:text-base " href="{{ product.get_absolute_url }}">{{ product.name | truncatechars:50 }}</p>
                  <div class="flex w-full justify-around items-center">
                    {% if product.discount  %} <p class="bg-red-800 text-white rounded-full h-5 w-8  font-bold text-center">%{{product.discount}}</p>{% endif %}

                      {% if product.discount != 0 %} 
                      <div class="priceTag">
                        <p class="text-red-800 line-through font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
                      
                      <p class="text-green-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{product.get_final_price | intcomma }} تومان</p>
                    </div>
                    {% else %}
                    <div class="priceTag">
                      <p class="text-green-800  font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
                  </div>
                      {% endif %}
                  </div>
                </div>
              </div>
          </a>
          {% endfor %}
        {% endfor %}
      </div>
      </div>
    </div>
    <div id="newest">
      <hr class="my-2">
      <div class="w-full flex justify-between px-10 font-AnjomanMax_Bold ">
        <h2>جدیدترین ها</h2>
        <h2><a class="my-4" href="{% url 'shop:product_list' %}">مشاهده همه</a></h2>
      </div>
    <div class="productBox">
    {% for product in products %}
    <a href="{{ product.get_absolute_url }}">
      <div class="item  mx-auto lg:mx-2  ">
          
            <img class="productImg" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
       
            <div class="productDetail">
              <p class="proname" >{{ product.name | truncatechars:75 }}</p>
              <div class="flex w-full justify-around ">
                {% if product.available == True %} <p class="text-green-500 text-sm">موجود  در انبار</p>{% else %} <p class="text-red-500 text-sm">موجود نیست</p>{% endif %}
              
                {% if product.discount != 0 %} 
                <div class="priceTag">
                  <p class="text-red-800 line-through font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
                <p class="text-red-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">%{{product.discount}}</p>
                <p class="text-green-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{product.get_final_price | intcomma }} تومان</p>
              </div>
              {% else %}
              <div class="priceTag">
                <p class="text-green-800  font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
  
            </div>
                {% endif %}
              </div>
            </div>
        </div>
      </a>
    {% endfor %}
  </div>
</div>
  <div class="mt-10">
    <div class="w-full text-center">
      <h2>
        خرید براساس دسته بندی
      </h2>
    </div>
    <div class="flex flex-wrap justify-center gap-4 px-2 lg:gap-12 lg:px-20 mt-4 lg:mb-20">
    {% for c in categories %}
        <div class="">
            <a class="text-center "  href="{{ c.get_absolute_url }}">
              <div class="size-16 lg:size-32 bg-gray-100 rounded-full overflow-visible justify-center items-center" >
                {% if c.image %}<img src="{{c.image.url}}" alt="">{% endif %}
              </div>
              <p class="mx-auto text-xs font-bold text-ellipsis w-16 lg:w-32">{{ c.name }}</p>
              </a>
    </div>
    {% endfor %}
  </div>
  </div>

  <div id="chipest">
    <hr class="my-2">
    <div class="w-full flex justify-between px-10 font-AnjomanMax_Bold ">
      <h2>ارزانترین ها </h2>
      <h2><a class="my-4" href="{% url 'shop:product_list' %}">مشاهده همه</a></h2>
    </div>
    <div class="productBox">
      {% for product in chipest %}
      <a href="{{ product.get_absolute_url }}">
        <div class="item  mx-auto lg:mx-2  ">
              <img class="productImg" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
         
              <div class="productDetail">
                <p class="proname" >{{ product.name | truncatechars:75 }}</p>
                <div class="flex w-full justify-around items-center">
                  {% if product.available == True %} <p class="text-green-500 text-sm">موجود  در انبار</p>{% else %} <p class="text-red-500 text-sm">موجود نیست</p>{% endif %}
                
                  {% if product.discount != 0 %} 
                  <div class="priceTag">
                    <p class="text-red-800 line-through font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
                  <p class="text-red-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">%{{product.discount}}</p>
                  <p class="text-green-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{product.get_final_price | intcomma }} تومان</p>
                </div>
                {% else %}
                <div class="priceTag">
                  <p class="text-green-800  font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
    
              </div>
                  {% endif %}
                </div>
              </div>
          </div>
        </a>
      {% endfor %}
    </div>
</div>
<div  id="popular">
  <hr class="my-2">
  <div class="w-full flex justify-between px-10 font-AnjomanMax_Bold ">
    <h2>محبوبترین ها</h2>
    <h2><a class="my-4" href="{% url 'shop:product_list' %}">مشاهده همه</a></h2>
  </div>
  <div class="productBox">
    {% for product in mid %}
    <a href="{{ product.get_absolute_url }}">
      <div class="item  mx-auto lg:mx-2  ">
            <img class="productImg" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
       
            <div class="productDetail">
              <p class="proname" >{{ product.name | truncatechars:75 }}</p>
              <div class="flex w-full justify-around items-center">
                {% if product.available == True %} <p class="text-green-500 text-sm">موجود  در انبار</p>{% else %} <p class="text-red-500 text-sm">موجود نیست</p>{% endif %}
              
                {% if product.discount != 0 %} 
                <div class="priceTag">
                  <p class="text-red-800 line-through font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
                <p class="text-red-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">%{{product.discount}}</p>
                <p class="text-green-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{product.get_final_price | intcomma }} تومان</p>
              </div>
              {% else %}
              <div class="priceTag">
                <p class="text-green-800  font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
  
            </div>
                {% endif %}
              </div>
            </div>
        </div>
      </a>
    {% endfor %}
  </div>
</div>
<div id="expensive">
  <hr class="my-2">
  <div class="w-full flex justify-between px-10 font-AnjomanMax_Bold ">
    <h2>گرانترین ها</h2>
    <h2><a class="my-4" href="{% url 'shop:product_list' %}">مشاهده همه</a></h2>
  </div>
  
  <div class="productBox">
    {% for product in expensive %}
    <a href="{{ product.get_absolute_url }}">
      <div class="item  mx-auto lg:mx-2  ">
            <img class="productImg" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
       
            <div class="productDetail">
              <p class="proname" >{{ product.name | truncatechars:75 }}</p>
              <div class="flex w-full justify-around items-center">
                {% if product.available == True %} <p class="text-green-500 text-sm">موجود  در انبار</p>{% else %} <p class="text-red-500 text-sm">موجود نیست</p>{% endif %}
              
                {% if product.discount != 0 %} 
                <div class="priceTag">
                  <p class="text-red-800 line-through font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
                <p class="text-red-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">%{{product.discount}}</p>
                <p class="text-green-800 font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{product.get_final_price | intcomma }} تومان</p>
              </div>
              {% else %}
              <div class="priceTag">
                <p class="text-green-800  font-AnjomanMax_Regular lg:font-AnjomanMax_Black">{{ product.price | intcomma }} تومان </p>
  
            </div>
                {% endif %}
              </div>
            </div>
        </div>
      </a>
    {% endfor %}
  </div>
</div>
</div>
  </div>
{% endblock %}