src/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("post_detail/<int:post_id>/", views.post_detail, name="post-detail"),
    path("like_post/<int:post_id>/", views.like_post, name="like-post"),
    path("add_comment/<int:post_id>/", views.add_comment, name="add-comment"),
    path(
        "add_reply/<int:post_id>/<int:comment_id>/", views.add_reply, name="add-reply"
    ),
    path(
        "delete_comment/<int:comment_id>/", views.delete_comment, name="delete-comment"
    ),
]

src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

src/coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

src/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path("back/account/", include("account.API.urls")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

src/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history/', views.history, name='history'),
    path(
        'admin/order/<int:order_id>/',
        views.admin_order_detail,
        name='admin_order_detail',
    ),
    path(
        'admin/order/<int:order_id>/pdf/',
        views.admin_order_pdf,
        name='admin_order_pdf',
    ),
]

src/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('aboutus', views.about, name='about'),
    path('list/', views.product_list, name='product_list'),
    path(
        'list/<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category',
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail',
    ),
    path('addorder/', views.add_order, name="add_order"),
    
]

src/cart/models.py
# Create your models here.

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label="تعداد"
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

src/cart/views.py
from coupons.forms import CouponApplyForm
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from shop.models import Product
# from shop.recommender import Recommender

from .cart import Cart
from .forms import CartAddProductForm

@login_required(login_url="account:login")
def cart_add(request, product_id):

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'],
        )
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):

    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True}
        )
    coupon_apply_form = CouponApplyForm()

    # r = Recommender()
    # cart_products = [item['product'] for item in cart]
    # if cart_products:
    #     recommended_products = r.suggest_products_for(
    #         cart_products, max_results=4
    #     )
    # else:
    #     recommended_products = []

    return render(
        request,
        'cart/detail.html',
        {
            'cart': cart,
            'coupon_apply_form': coupon_apply_form,
            # 'recommended_products': recommended_products,
        },
    )

src/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  سبد خرید 
{% endblock %}

{% block content %}
<div class="px-2 pt-14 lg:pt-20 min-h-screen">

      {% for item in cart %}
        {% with product=item.product %}
         <div class="flex border-t">

            <div class="w-1/2 p-4 flex justify-center items-center">
              <a href="{{ product.get_absolute_url }}">
                <img class="w-full lg:size-40 border border-gray-300" src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </div>
            <div class="w-1/2 py-4">
              <p>{{ product.name }}</p>
              <div class="w-full px-4 text-left lg:text-right lg:my-4">
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.override }}
                  <input class="w-24 primary_btn" type="submit" value="بروزرسانی">
                  {% csrf_token %}
                </form>

                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                  <input class="w-24 mt-4 bg-red-300 rounded-md shadow shadow-red-500" type="submit" value="Remove">
                  {% csrf_token %}
                </form>
              </div>
              

              <div>
                <p>قیمت هر واحد</p>
                <p class="text-blue-600">{{ item.price }} تومان</p>
              </div>
              <div>
                <p>قیمت کل</p>
                <p class="text-blue-800">{{ item.total_price }} تومان</p>
              </div>
          </div>
        {% endwith %}
      </div>
      {% endfor %}
      <div class="p-4">
        <hr>
        {% if cart.coupon %}
    
        <p>جمع</p>

        <p class="num">{{ cart.get_total_price}} تومان</p>

          "{{ cart.coupon.code }}" تخفیف
          ({{ cart.coupon.discount }}% off)

          - تومان{{ cart.get_discount }}

    {% endif %}

      <p>جمع کل</p>

       <p class="text-green-600"> {{ cart.get_total_price_after_discount }} تومان</p>
      </div>


  

<div>
  <p>اعمال تخفیف</p>
  <form class="flex items-center bg-gray-300" action="{% url "coupons:apply" %}" method="post">
    {{ coupon_apply_form }}
      <input class="w-32 primary_btn my-4" type="submit" value="اعمال">
    {% csrf_token %}
  </form>
</div>

  <div class="text-center my-4 w-full flex justify-start ">
    <a href="{% url 'shop:product_list' %}" class="w-32 primary_btn">ادامه خرید</a>
    <a href="{% url 'orders:order_create' %}" class="w-32 succes_btn mx-4">پرداخت</a>
  </div>
</div>
{% endblock %}