src/account/urls.py
from django.urls import path


from . import views

app_name = "account"

urlpatterns = [
    path("logout/", views.logout_user, name="logout"),
    path("signup/<str:code>/", views.signup, name="signup"),
    path("login/", views.login_user, name="login"),
    path("login_s/", views.login_with_sms, name="login_s"),
    path("verify/<str:dir>/", views.verify, name="verify"),
    path("forgetPass/<str:code>/", views.forgetPass, name="forgetPass"),
    path("UpdateAccount/", views.UpdateAccount, name="UpdateAccount"),

   
]

src/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post-list"),
    path("post_detail/<int:post_id>/", views.post_detail, name="post-detail"),
    path("like_post/<int:post_id>/", views.like_post, name="like-post"),
    path("add_comment/<int:post_id>/", views.add_comment, name="add-comment"),
    path(
        "add_reply/<int:post_id>/<int:comment_id>/", views.add_reply, name="add-reply"
    ),
    path(
        "delete_comment/<int:comment_id>/", views.delete_comment, name="delete-comment"
    ),
]

src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

src/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    path("back/account/", include("account.API.urls")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

src/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history/', views.history, name='history'),
    path(
        'admin/order/<int:order_id>/',
        views.admin_order_detail,
        name='admin_order_detail',
    ),
    path(
        'admin/order/<int:order_id>/pdf/',
        views.admin_order_pdf,
        name='admin_order_pdf',
    ),
]

src/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('aboutus', views.about, name='about'),
    path('list/', views.product_list, name='product_list'),
    path(
        'list/<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category',
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail',
    ),
    path('addorder/', views.add_order, name="add_order"),
    
]

src/shop/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import Account

# class crm(models):
#     phone = models.CharField(max_length=13)
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    image = models.ImageField(
        upload_to='Category/',
        blank=True
    )
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category', args=[self.slug]
        )


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    image2 = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )
    size = models.CharField(max_length=100, blank=True, null=True)
    weight = models.CharField(max_length=100, blank=True, null=True)
    deliveryTime= models.CharField(max_length=100, blank=True, null=True)
    description = RichTextUploadingField(blank=True)
    Specifications = RichTextUploadingField(blank=True)
    price = models.PositiveBigIntegerField(default=0)
    discount = models.PositiveBigIntegerField(default=0, max_length=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    def get_final_price(self):
        return abs(int((self.price * (self.discount - 100)) / 100))
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])




class SpecialOrder(models.Model):

    user = models.ForeignKey(Account,  related_name='special',null=True,  on_delete=models.SET_NULL)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to="SpecialOrder/", null=True, blank=True)

    class Meta:
        verbose_name = "سفارش"
        verbose_name_plural = "سفارش ها"

    def __str__(self):
        return self.name




class SpecialSale(models.Model):
    products = models.ManyToManyField(Product, related_name="special")

    

src/shop/forms.py
from django import forms

from shop.models import SpecialOrder




class addOrderForm(forms.ModelForm):
    class Meta:
        model = SpecialOrder
        fields = (
            "name",
            "phone",
            "description",
            "image"
        )

    def save(self, commit=True, *args, **kwargs):
        order = super().save(commit=False)
        if commit:
            order.save()

        return order

src/shop/views.py
from django.shortcuts import get_object_or_404, redirect, render

from cart.forms import CartAddProductForm
from shop.forms import addOrderForm
from .models import Category, Product,SpecialSale
from django.views.generic import  ListView
from django.db.models import Q 
# from .recommender import Recommender
class SearchResultsView(ListView):
    model = Product
    template_name = 'shop/product/search_results.html'
    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
  
        return object_list
def add_order(request):

    if request.method == 'POST':
        form = addOrderForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
        return redirect("shop:home")
    return redirect("shop:home")


def home(request):
    All = Product.objects.all()
    length = len(All)
    products = All.filter(available=True)[:4]
    chipest = All.order_by("price")[:4]
    special =SpecialSale.objects.all()[:1]
    mid = All.order_by("price")[length/2-3:length/2+1]
    categories = Category.objects.all()
    expensive = All.order_by("-price")[:4]
    return render(
        request,
        'shop/product/home.html',
        {
            'products': products,
            'chipest': chipest,
            'categories': categories,
            'mid': mid,
            'special':special,
            'expensive': expensive,
        },)
def product_list(request, category_slug=None):

    category = None
    categories = Category.objects.all()

    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
           
        },
    )


def product_detail(request, id, slug):

 
    product = get_object_or_404(
        Product, id=id, slug=slug
    )
    cart_product_form = CartAddProductForm()
    # r = Recommender()
    # recommended_products = r.suggest_products_for([product], 4)
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form,
            
            # 'recommended_products': recommended_products,
        },
    )

def about(request):
    return render(request, "shop/aboutus.html")

src/templates/shop/components/Hero.html
{% load static %}

<section class="w-full md:w-[80%] h-[100vh] md:h-[80vh] md:max-h-[780px] md:mt-20 lg:mt-24 mb-10  mx-auto">
    {# card #}
    <div class="relative flex flex-col h-full md:rounded-xl shadow-[0_12px_40px_rgba(0,0,0,.25)] shadow-secondary/50">
        {#card image#}
        <div class="h-2/3 relative md:rounded-t-xl overflow-hidden">
            <img src="{% static 'img/banner.jpg' %}" class="w-full h-full object-cover object-top bg-secondary-600">
            <div class="w-full text-center md:text-start h-2/3 bg-gradient-to-t from-secondary to-transparent absolute flex flex-col justify-end p-8"
                 style="bottom: -3px">
                <h1 class="font-bold text-3xl md:text-4xl text-white lg:text-6xl">
                    محصولات برنز ارسی 
                </h1>
            </div>
        </div>
        {#card body#}
        <div class="h-2/5 md:h-1/3 bg-secondary text-white text-center md:text-start px-8 md:rounded-b-xl">
            <div class="md:w-1/2 flex flex-col gap-6 md:gap-7">
                <h4 class="text-xl lg:text-2xl font-medium" style="line-height: 1.5">ساخت و طراحی وسایل برنزی منزل <br/> لوستر ، مبلمان (برنز)</h4>

                    <a class="w-fit mx-auto md:mx-0 button font-medium text-xl bg-violet-300 px-10 before:bg-white text-black"
                       href="{% url 'shop:product_list' %}" title="شروع خرید"><i class="fa-solid fa-play animate-pulse text-amber-200"></i>
                       همه محصولات</a>
                

                <button onclick="scrollDown()" class="md:hidden"><span
                        class="text-white text-xl flex items-end justify-center gap-1 hover:gap-2 transition-all"> اطلاعات بیشتر<i
                        class="fa-solid fa-chevron-down animate-bounce animate-infinite animate-ease-in-out"></i></span>
                </button>
            </div>
        </div>
        {#card popup#}
        <div class="hidden md:flex absolute -left-10 xlg:-left-16 bottom-10 md:w-1/3 rounded-2xl bg-white xlg:w-2/5 2xl:w-1/4 min-h-2/4 shadow-[0_12px_20px_rgba(0,0,0,.12)] p-5 px-10 py-7 flex-col gap-7">
            <img src="{% static "img/luster-53.jpg" %}" alt="">
        </div>
    </div>
</section>

<script>
    function scrollDown() {
        // Scroll the remaining height to reach 100% of the viewport height
        const currentScroll = window.scrollY;
        const viewportHeight = window.innerHeight;
        const scrollAmount = viewportHeight - (currentScroll % viewportHeight) - 60;

        window.scrollBy({
            top: scrollAmount,
            behavior: 'smooth'
        });
    }
</script>

src/templates/shop/components/_footer.html
<footer class=" flex w-full items-center justify-center bg-gray-800 h-40">
    <p class="text-white"><span class="text-white">&copy; <a
            class="text-yellow-500 hover:text-blue-400 font-persianBold text-lg" href="#">  محصولات برنز ارسی </a></span> | تمامی
        حقوق محفوظ است.</p>
        <div class="w-24 lg:w-40 mx-10">
            <img referrerpolicy='origin' id = 'rgvjjzpergvjjxlzapfujxlz' style = 'cursor:pointer' onclick = 'window.open("https://logo.samandehi.ir/Verify.aspx?id=373151&p=xlaojyoexlaorfthdshwrfth", "Popup","toolbar=no, scrollbars=no, location=no, statusbar=no, menubar=no, resizable=0, width=450, height=630, top=30")' alt = 'logo-samandehi' src = 'https://logo.samandehi.ir/logo.aspx?id=373151&p=qftiyndtqftinbpdujynnbpd' />
        </div>
        <div class="w-24 lg:w-40 ">
        <a referrerpolicy='origin' target='_blank' href='https://trustseal.enamad.ir/?id=535521&Code=UjPWkz7FXBF6Ucb45djNgHrCYzTsvqzq'><img referrerpolicy='origin' src='https://trustseal.enamad.ir/logo.aspx?id=535521&Code=UjPWkz7FXBF6Ucb45djNgHrCYzTsvqzq' alt='' style='cursor:pointer' code='UjPWkz7FXBF6Ucb45djNgHrCYzTsvqzq'></a>
    </div>
    </footer>

src/templates/shop/components/_header.html
{% load static %}
<style>
    .header {
        position: fixed;
        top: 56px;
        left: 0;
        width: 100%;
        transition: 0.5s ease-in-out;
        z-index: 10;
    }

    .header.sticky {
        position: fixed;
        top: -100px;
        left: 0;
        width: 100%;
        z-index: 10;
    }

    #mobile-nav {
        height: 100dvh;
        height: 100vh;
    }

    #mobile-nav.show {
        display: flex;
        transform: translateX(0%);
    }

    #backdrop {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.7);
        transition: display 0.3s ease;
    }

    #backdrop.show {
        display: block;
    }

</style>
<header class="mx-auto header bg-white w-full relative px-4 py-2 lg:px-6 2xl:px-8 shadow-[0_4px_20px_0px_rgba(41,144,251,.12)]">

    <div class="flex w-full justify-between items-center max-w-7xl mx-auto gap-5">
        {#  toggle mobile nav btn  #}
        <div class="flex items-start justify-start w-1/4 lg:hidden">
            <i class="fa-solid fa-bars text-2xl cursor-pointer" onclick="toggleMobileMenu()"></i>
        </div>

        {#  Desktop navbar  #}
        <nav id="navbar"
             class="hidden lg:block lg:flex-row w-full bg-transparent justify-center items-center lg:justify-between">
            <div class="w-full items-center">
                <ul class="w-full text-base flex gap-4">
                    <li><a class="hover:text-primary transition-all font-medium nav-link"
                        href="{% url 'shop:home' %}">
                     <i class="fas fa-home"></i> خانه </a></li>
                    |
                    <li><a class="hover:text-primary transition-all font-medium nav-link"
                           href="{% url 'shop:product_list' %}">
                        <i class="fas fa-list"></i>دسته بندی</a></li>
                    |
                    <li><a class="hover:text-primary transition-all font-medium nav-link"
                           href="{% url 'blog:post-list' %}">
                        <i class="fas fa-book"></i> مجله   محصولات برنز ارسی</a></li>
                    |
                    <li><a class="hover:text-primary transition-all font-medium nav-link"
                            href="{% url 'shop:about' %}">
                            <i class="fas fa-info-circle"></i>تماس با ما</a></li>
                </ul>
            </div>
        </nav>
        {#  Soorchi logo  #}
        <div class="flex items-center justify-end lg:justify-start w-1/6 lg:order-first">
            <div class="cart">
                {% with total_items=cart|length %}
                  {% if total_items > 0 %}
                  <a class="relative" href="{% url 'cart:cart_detail' %}">
                    <img src="{% static 'img/logo.png' %}" 
                        class="w-full object-contain rounded-xl animate-wiggle hover:animate-spin  animate-infinite animate-ease-in-out transition-all h-[40px] lg:h-[50px] -z-10">

                      <p class="absolute size-7 flex justify-center items-center rounded-full bg-red-700 text-white font-AnjomanMax_Black -mt-5 -mr-4 z-20">{{ total_items }}</p>
                    </a>
                  {% elif not order %}
                  <img src="{% static 'img/logo.png' %}" onclick="alert('سبد شما خالی است')"
                        class="w-full object-contain rounded-xl animate-wiggle hover:animate-spin  animate-infinite animate-ease-in-out transition-all h-[40px] lg:h-[50px]"
                  alt="logo">
                  {% endif %}
                {% endwith %}
              </div>
           
            </a>
        </div>
        <!-- {#  Desktop Login btn  #} -->
        <button class="hidden lg:flex w-52" onclick="modal('1')"><a class="hover:text-primary transition-all font-medium nav-link"
          >
         <i class="fas fa-pen"></i>سفارش اختصاصی </a> </button>
        <!-- {#  Mobile navbar  #} -->
        <div id="mobile-nav"
             class="fixed flex-col justify-between items-center w-[80%] bg-white text-black right-0 top-0 p-[2.5rem] transform translate-x-[100%] gap-5 transition-transform duration-300 ease shadow"
             style="z-index: 12;">
            <div class="h-30 w-full mt-4 flex justify-end cursor-pointer" onclick="toggleMobileMenu()">
                <i class="fa-solid fa-xmark text-2xl"></i>
            </div>

            <ul class="gap-12 flex flex-col justify-start items-start h-[60vh] mt-5 overflow-y-auto">
                <li><a class="hover:text-primary transition-all font-medium nav-link" href="{% url 'shop:home' %}"><i
                        class="fas fa-home"></i> خانه </a></li>
                <li><a class="hover:text-primary transition-all font-medium nav-link" href="{% url 'shop:product_list' %}"><i
                        class="fas fa-list"></i> دسته بندی </a></li>
                <li><a class="hover:text-primary transition-all font-medium nav-link" href="{% url 'blog:post-list' %}"><i
                        class="fas fa-book"></i> مجله   محصولات برنز ارسی </a></li>
                <li><a class="hover:text-primary transition-all font-medium nav-link" href="{% url 'shop:about' %}"><i
                            class="fas fa-info-circle ml-1"> </i>تماس با ما </a></li>
            </ul>


            <div class="h-[15vh] flex flex-col justify-end w-full gap-2">
                <button class="flex  bottom-5 right-5 primary_btn w-" onclick="modal('1')">سفارش اختصاصی</button>
                {% if user.is_authenticated %}
                   <a class="btn w-full flex justify-center bg-primary px-5 before:bg-primary-500 text-white"
                       href="#" title="داشبورد"><i class="fa-solid fa-user"></i>
                        <p class="mx-2">{{user.first_name}}</p></a> 
                    
                    <a class="btn w-full bg-red-400 px-5 before:bg-red-300"
                       title="خروج"
                       href="{% url 'account:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket text-lg"></i>
                        خروج از حساب
                    </a>
                {% else %}
                    <a href="{% url 'account:login' %}"
                       class="btn w-full bg-primary px-10 before:bg-primary-500 text-white text-sm">
                        ورود | ثبت نام
                    </a>
                {% endif %}
            </div>
        </div>
        {#    mobile navbar backdrop    #}
        <div id="backdrop" style="z-index: 11;" onclick="toggleMobileMenu()"></div>
    </div>

</header>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const links = document.querySelectorAll(".nav-link");

        // Get the current URL path
        const currentPath = window.location.pathname.split('/')[1];

        links.forEach(link => {
            const linkPath = link.getAttribute("href").split('/')[1];
            if (linkPath === currentPath) {
                link.classList.add("text-primary");
            }
        });
    });

    function toggleMobileMenu() {
        const mobileNav = document.getElementById('mobile-nav');
        const backdrop = document.getElementById('backdrop');
        mobileNav.classList.toggle('translate-x-[100%]');
        backdrop.classList.toggle('show');
        document.body.classList.toggle('overflow-hidden');
    }
</script>

src/templates/shop/components/_search.html
<div class="w-full h-14 flex justify-around items-center z-20 fixed top-0 bg-white">


  <form class="flex justify-center items-center"  action="{% url 'shop:search_results' %}" method="get">
      <input class="w-full border h-12 rounded-xl mr-2 px-2" name="q" type="text" placeholder="جستجو...">
      <button class="link px-4 mx-2" type="submit">جستجو</button>

    </form>
    
    <div class="hidden lg:flex items-end justify-end lg:justify-end gap-6 h-full">
      {% if user.is_authenticated %}
          <a class="flex items-center h-full text-center rounded-full my-auto" title="خروج"
            href="{% url 'account:logout' %}"><i class="fa-solid fa-arrow-right-from-bracket text-2xl"></i>
          </a>
          <a class="btn flex w-fit bg-primary px-5 before:bg-primary-500 text-white"
            href="{% url 'orders:history' %}" title="داشبورد"><i class="fa-solid fa-user"></i>
              <p class="mx-2">{{user.first_name}}</p></a>
      {% else %}
          <a href="{% url 'account:login' %}"
            class="btn bg-primary w-40 before:bg-primary-500 text-white text-sm">
              ورود | ثبت نام
          </a>
      {% endif %}
  </div>

</div>